jobs:
  - deployment: job1
    variables:
      p1Arg: 'FirstArgument'
      p3Arg: 'Third Argument'
    pool: default
    environment: Env1.RG1
    strategy:
        rolling:
          deploy:
            steps:
              - script: echo Hello, world! $(p1Arg) $(p3Arg) $(hello)
                displayName: 'Run a one-line script'
