jobs:
  - deployment: job1
    variables:
      p1Arg: 'FirstArgument'
      p3Arg: 'Third Argument'
    pool: Hosted
    environment: ajyaenvironment1
    strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureCLI@1
                inputs:
                  azureSubscription: 'ajya_spn'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'Write-output "hello"'
                  displayName: 'Run a one-line script'
