name: Ajay

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: stage_1
  displayName: 'Stage 1 - Provision resources to feature environment'
  jobs:
  - deployment: Job1
    pool: 'default'
    environment: env1
    strategy:
        runOnce:
          deploy:
            steps:
            - script: echo execute job1 on stage 1
              displayName: 'Feature environment provisioning'
- stage: stage_2
  displayName: 'Stage 2 demo'
  jobs:
  - deployment: Job2
    pool: 'default'
    environment: env1
    strategy:
        runOnce:
          deploy:
            steps:
            - script: echo execute job2 on stage 2
              displayName: 'Job1 on stage1 demo'
- stage: stage_3
  displayName: 'Stage 3 thunder'
  jobs:
  - deployment: Job3
    pool: 'default'
    environment: env1
    strategy:
        runOnce:
          deploy:
            steps:
              - script: echo execute job3 on stage 3
                displayName: 'Thunder and lightening job'
